namespace: epfl_si
name: git
version: 0.1.0
readme: README.md
authors:
    - "EPFL IDEV-FSD <idev-fsd@groupes.epfl.ch>"
license:
    - "MIT"
tags:
    - git

repository: "https://github.com/epfl-si/ansible-collection-git"
dependencies:
  epfl_si.actions: ">=0.2.0"
