namespace: epfl_si
name: git
version: 0.2.0
readme: README.md
description: Enforce postconditions on a Git repository (e.g. committed, pushed, pulled)
authors:
    - "EPFL IDEV-FSD <idev-fsd@groupes.epfl.ch>"
license:
    - "MIT"
tags:
    - git

repository: "https://github.com/epfl-si/ansible-collection-git"
dependencies:
  epfl_si.actions: ">=1.0.0"
